// flow-typed signature: a009cab568aef533430744cb7f567b4f
// flow-typed version: <<STUB>>/postcss-fixes_v^1.4.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-fixes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-fixes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-fixes/index' {
  declare module.exports: $Exports<'postcss-fixes'>;
}
declare module 'postcss-fixes/index.js' {
  declare module.exports: $Exports<'postcss-fixes'>;
}
